### DISCUSSION TITLE
Connectivity lost after Gluetun restart

### DISCUSSION THREAD

**Discussion by Manfred73** [qdm12/deunhealth#34] [General]
I was reading this discussion: https://githubhot.com/repo/qdm12/gluetun/issues/641?page=1 which led me to this deunhealth project.
I ran into the same problem, after restarting glueton, I was no longer able to access deluge until I restarted deluge as well and reconnected to the daemon.

I'm using watchtower for updating my docker images, so if glueton is updated, this problem may also occur.

Is it already possible to use deunhealth to solve this?

Do I need to add anything like deunhealth.restart.on.unhealthy=true in my docker containers which are dependent on Glueton?

**Comment by Manfred73** [comment]
I installed the deunhealth image and added a label to my docker compose file, but it doesn't seem to work after I restart gluetun:

```
services:
  deluge:
    container_name: deluge
    image: lscr.io/linuxserver/deluge
    labels:
      - deunhealth.restart.on.unhealthy=true
    ............
```
Did I put the labels in the correct place / correct notation?
By the way: I'm running this image on a QNAP with Intel(R) Xeon(R) W-1250 CPU
