### ISSUE TITLE
Feature request: Add option to force container re-create rather than restart

### ISSUE THREAD

**Issue by oester** [qdm12/deunhealth#16]
If you have a service configured similar to the following:

```
network_mode: "container:gluetun"
    healthcheck:
      test: "curl -sf https://google.com  || exit 1"
      interval: 1m
      timeout: 10s
      retries: 1
    labels:
      - deunhealth.restart.on.unhealthy=true
```

And the gluetun container is re-created due to a new version, the using container is marked as "unhealthy" but a container restart won't work because the container ID of the gluetun container is changed.

Consider adding an option "deunhealth.recreate.on.unhealthy=true" to resolve this.
