### ISSUE TITLE
Feature request: auto-restart of containers contains depends_on when the parent container will be restart

### ISSUE THREAD

**Issue by PiDroid-B** [qdm12/deunhealth#49]
**context**

When we have containers depend on (aka childs) one other container (parent), the childs doesn't restart when the parent failed and restart.

```yaml
services:
  parent_container:
      labels:
      - deunhealth.restart.on.unhealthy=true
     [...]
     
  child1:
    depends_on:
      parent_container:
        condition: service_healthy
      network_mode: "service:parent_container"
      labels:
      - deunhealth.restart.on.unhealthy=true    
     [...]        

  child2:
    depends_on:
      parent_container:
        condition: service_healthy
      network_mode: "service:parent_container"
      labels:
      - deunhealth.restart.on.unhealthy=true
     [...]        
```

**What's the feature?** 🧐

- Add a solution to check childs when a restart of the parent is required and restart them when parent is "running" and/or "healthly".

**Suggested solution**

Maybe something like that :

- add a label for child : deunhealth.restart.on.depends_on=true
(maybe change "true" to the parent's container_name)

- workflow of auto-restart parent :
  - restart the container (parent)
  - get list of other containers contains the according label (childs)
    - if state is not running/healthly then restart it

Thank's for your help.
